export * from './client.js'

// Re-export all Prisma-generated types so consumers only need @shital/db
export type {
  User,
  Session,
  OtpCode,
  AuditLog,
  Branch,
  Account,
  Transaction,
  TransactionLine,
  GiftAidDeclaration,
  Donation,
  Budget,
  BudgetLine,
  Employee,
  LeavePolicy,
  LeaveRequest,
  TimeEntry,
  PayrollRun,
  PayslipLine,
  Asset,
  MaintenanceRecord,
  TempleService,
  ServiceBooking,
  Document,
  DocumentAccess,
  GovernanceDocument,
  TrusteeDeclaration,
  Notification,
  Basket,
  BasketItem,
  Order,
  // Enums
  Role,
  OtpPurpose,
  AccountType,
  TransactionStatus,
  PaymentProvider,
  DonationStatus,
  BudgetStatus,
  EmploymentType,
  SalaryPeriod,
  LeaveType,
  LeaveStatus,
  PayrollRunStatus,
  AssetCategory,
  AssetStatus,
  MaintenanceStatus,
  ServiceCategory,
  BookingStatus,
  BookingPaymentProvider,
  DocumentCategory,
  DocumentPermission,
  GovernanceDocumentType,
  GovernanceDocumentStatus,
  DeclarationType,
  NotificationType,
  NotificationChannel,
  BasketStatus,
  BasketItemType,
  OrderStatus,
  OrderPaymentProvider,
  // Prisma namespace for input/output types
  Prisma,
} from '@prisma/client'
